# MATRIX OPERATIONS

In [16]:
import numpy as np
#create matrix
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
#ADDITION
C=A+B
#SUBSTRACTION
D=A-B
#MULTIPLICATION(element-wise)
E=A*B
#MATRIX MULTIPLICATION
F=np.dot(A,B) # or A @ B
#TRANSPOSE
A_transpose=A.T
B_transpose=B.T
print("ADDITION                     \n",C)
print("\nSUBSTRACTION                 \n",D)
print("\nMULTIPLICATION(element-wise) \n",E)
print("\nMATRIX MULTIPLICATION        \n",F)
print("\nTRANSPOSE \n",A_transpose)
print("\n",B_transpose)

ADDITION                     
 [[ 6  8]
 [10 12]]

SUBSTRACTION                 
 [[-4 -4]
 [-4 -4]]

MULTIPLICATION(element-wise) 
 [[ 5 12]
 [21 32]]

MATRIX MULTIPLICATION        
 [[19 22]
 [43 50]]

TRANSPOSE 
 [[1 3]
 [2 4]]

 [[5 7]
 [6 8]]



# SVD

In [2]:
import numpy as np

#creating sample matrix
X=np.array([[1,2,3],[4,5,6],[7,8,9]])

#perform SVD
U,S,VT=np.linalg.svd(X)

#choose the numb of compnents to keep (eg;2)
n_components=2

#reconstruct the  matrix with reduced dimensions
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("Original Matrix :")
print(X)
print("\nReconstruct Matrix(with reduced dimensions):")
print(X_reconstructed)


Original Matrix :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstruct Matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
